databaseChangeLog:
  - changeSet:
      id: insert-global-settings-data
      author: Sergey Sh
      changes:
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: code
                  value: 'MULTIUSER_MODE'
              - column:
                  name: name
                  value: 'Многопользовательский режим'
              - column:
                  name: value
                  value: 'true'
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: code
                  value: 'POST_PREMODERATION'
              - column:
                  name: name
                  value: 'Премодерация постов'
              - column:
                  name: value
                  value: 'true'
        - insert:
            tableName: global_settings
            columns:
              - column:
                  name: id
                  value: 3
              - column:
                  name: code
                  value: 'STATISTICS_IS_PUBLIC'
              - column:
                  name: name
                  value: 'Показывать статистику'
              - column:
                  name: value
                  value: 'true'