server:
  port: 8088

spring:
  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/myblog?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;connectionCollation=utf8_general_ci&amp;characterSetResults=UTF-8
    username: postgres
    password: root1289User
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQL9Dialect
#      show_sql: true
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob: non_contextual_creation=true
#      generate-ddl: false
#      show-sql: true
#      open-in-view: false



blog:
 details:
   title: Sergey Shibko
   subtitle: Мой Блог
   phone: +7 914 905-70-65
   email: serje_fox@mail.ru
   copyright: Sergey Shibko
   copyrightFrom: 2022
